# Images

In [1]:
import cv2
import numpy as np

In [9]:
#with imread, we're only reading an image.
img = cv2.imread("lena.jpg", 0) 
# 1:Loads a colored image
# 0 :Loads image in grayscale mode
# -1:Loads images as such including alpha channel
print(img)

[[163 162 161 ... 170 154 130]
 [162 162 162 ... 173 155 126]
 [162 162 163 ... 170 155 128]
 ...
 [ 43  42  51 ... 103 101  99]
 [ 41  42  55 ... 103 105 106]
 [ 42  44  57 ... 102 106 109]]


In [10]:
#we're displaying images with imshow method.
cv2.imshow("image",img) # it just displays image for milisecond.
cv2.waitKey() #how many miliseconds is it going to be displayed #if we write 0 as an argument, it won't be closed until we click close button.
cv2.destroyAllWindows() #to close windows

In [4]:
cv2.imwrite("berkay_copy.png",img) #it is creating a copy of image that we're working on.

True

# Videos

In [14]:
cap = cv2.VideoCapture(0)


while(True):
    ret,frame = cap.read() #ret may take true or false , frame is the video of your camera
    
   
    cv2.imshow("PixelBusters",frame)
    
    if cv2.waitKey(1) & 0xFF == ord("q"): #if you press the Q button when frame is opening, it will be closed. 
        break
        
cap.release()
cv2.destroyAllWindows()

In [16]:
cap = cv2.VideoCapture(0)


while(True):
    ret,frame = cap.read() #ret may take true or false , frame is the video of your camera
    
    gray = cv2.cvtColor(frame, cv2.COLOR_BGR2GRAY) #colored to gray
    
    
    cv2.imshow("PixelBusters", gray)
    
    if cv2.waitKey(1) & 0xFF == ord("q"): #if you press the Q button when frame is opening, it will be closed. 
        break
        
cap.release()
cv2.destroyAllWindows()

In [17]:
cap = cv2.VideoCapture(0)
print(cap.isOpened())



while(cap.isOpened()): #if you give 0 value in videocapture method cap.isopened return you True value.
    ret,frame = cap.read() #ret may take true or false , frame is the video of your camera
    
    print(cap.get(cv2.CAP_PROP_FRAME_WIDTH)) #to get frame width
    print(cap.get(cv2.CAP_PROP_FRAME_HEIGHT)) #to get frame height
    
    gray = cv2.cvtColor(frame, cv2.COLOR_BGR2GRAY) #colored to gray
    
    
    cv2.imshow("frame", gray)
    
    if cv2.waitKey(1) & 0xFF == ord("q"): #if you press the Q button when frame is opening, it will be closed. 
        break
        
cap.release()
cv2.destroyAllWindows()

True
640.0
480.0
640.0
480.0
640.0
480.0
640.0
480.0
640.0
480.0
640.0
480.0
640.0
480.0
640.0
480.0
640.0
480.0
640.0
480.0
640.0
480.0
640.0
480.0
640.0
480.0
640.0
480.0
640.0
480.0
640.0
480.0
640.0
480.0
640.0
480.0
640.0
480.0
640.0
480.0
640.0
480.0
640.0
480.0
640.0
480.0
640.0
480.0
640.0
480.0
640.0
480.0
640.0
480.0
640.0
480.0
640.0
480.0
640.0
480.0
640.0
480.0
640.0
480.0
640.0
480.0
640.0
480.0
640.0
480.0
640.0
480.0
640.0
480.0
640.0
480.0
640.0
480.0
640.0
480.0
640.0
480.0
640.0
480.0
640.0
480.0
640.0
480.0
640.0
480.0
640.0
480.0
640.0
480.0
640.0
480.0
640.0
480.0
640.0
480.0
640.0
480.0
640.0
480.0
640.0
480.0
640.0
480.0
640.0
480.0
640.0
480.0
640.0
480.0
640.0
480.0
640.0
480.0
640.0
480.0
640.0
480.0
640.0
480.0
640.0
480.0
640.0
480.0
640.0
480.0
640.0
480.0
640.0
480.0
640.0
480.0
640.0
480.0
640.0
480.0
640.0
480.0
640.0
480.0
640.0
480.0
640.0
480.0
640.0
480.0
640.0
480.0
640.0
480.0
640.0
480.0
640.0
480.0
640.0
480.0
640.0
480.0
640.0
480.0
640.0
480.0

In [18]:
cap = cv2.VideoCapture(0)
fourcc = cv2.VideoWriter_fourcc(*"XVID")
out = cv2.VideoWriter("output.avi",fourcc,20.0,(640,480)) #20 = number of frames per second



print(cap.isOpened())



while(cap.isOpened()): #if you give 0 value in videocapture method cap.isopened return you True value.
    ret,frame = cap.read() #ret may take true or false , frame is the video of your camera
    
    if ret == True:
    
        print(cap.get(cv2.CAP_PROP_FRAME_WIDTH)) #to get frame width
        print(cap.get(cv2.CAP_PROP_FRAME_HEIGHT)) #to get frame height
        
        out.write(frame) #it will be saved in original format,because this line of is coming from before converting color code.
    
        gray = cv2.cvtColor(frame, cv2.COLOR_BGR2GRAY) #colored to gray
    
    
        cv2.imshow("frame", gray)
    
        if cv2.waitKey(1) & 0xFF == ord("q"): #if you press the Q button when frame is opening, it will be closed. 
            break
    else:
        break
        
cap.release()
out.release()
cv2.destroyAllWindows()

True
640.0
480.0
640.0
480.0
640.0
480.0
640.0
480.0
640.0
480.0
640.0
480.0
640.0
480.0
640.0
480.0
640.0
480.0
640.0
480.0
640.0
480.0
640.0
480.0
640.0
480.0
640.0
480.0
640.0
480.0
640.0
480.0
640.0
480.0
640.0
480.0
640.0
480.0
640.0
480.0
640.0
480.0
640.0
480.0
640.0
480.0
640.0
480.0
640.0
480.0
640.0
480.0
640.0
480.0
640.0
480.0
640.0
480.0
640.0
480.0
640.0
480.0
640.0
480.0
640.0
480.0
640.0
480.0
640.0
480.0
640.0
480.0
640.0
480.0
640.0
480.0
640.0
480.0
640.0
480.0
640.0
480.0
640.0
480.0
640.0
480.0
640.0
480.0
640.0
480.0
640.0
480.0
640.0
480.0
640.0
480.0
640.0
480.0
640.0
480.0
640.0
480.0
640.0
480.0
640.0
480.0
640.0
480.0
640.0
480.0
640.0
480.0
640.0
480.0
640.0
480.0
640.0
480.0
640.0
480.0
640.0
480.0
640.0
480.0
640.0
480.0
640.0
480.0
640.0
480.0
640.0
480.0
640.0
480.0
640.0
480.0
640.0
480.0
640.0
480.0
640.0
480.0
640.0
480.0
640.0
480.0
640.0
480.0
640.0
480.0
640.0
480.0
640.0
480.0
640.0
480.0
640.0
480.0
640.0
480.0
640.0
480.0
640.0
480.0
640.0
480.0

# Drawing Geometric Shapes

In [19]:
img = cv2.imread("lena.jpg",0)

cv2.imshow("image",img)

cv2.waitKey(0)
cv2.destroyAllWindows()

In [20]:
img = cv2.imread("lena.jpg",0)

img = cv2.line(img, (0,0) , (255,255) , (0,0,255) ,5) #arguments : img,starting point,ending point,(blue,green,red),thickness
#because this image displays in a grayscale you can see a black line instead of red line

cv2.imshow("image",img)

cv2.waitKey(0)
cv2.destroyAllWindows()

In [21]:
img = cv2.imread("lena.jpg",1) #image is readed in colored format so you can see a red line in the image.

img = cv2.line(img, (0,0) , (255,255) , (0,0,255) ,10) #arguments : img,starting point,endin point,(blue,green,red),thickness
#if you want to draw a different colored line, search rgb color on google but be careful because in opencv we use bgr respectively.
img =  cv2.arrowedLine(img, (0,255) , (255,255) , (41,205,95) ,10)
#arrowedLine drawing an arrowed line.
img = cv2.rectangle(img,(384,0),(510,128),(0,0,255),5) #point 1:top-left , point2 :bottom-right
#this code enables drawing a rectangle. 


cv2.imshow("image",img)

cv2.waitKey(0)
cv2.destroyAllWindows()

In [22]:
img = cv2.imread("lena.jpg",1) 

img = cv2.line(img, (0,0) , (255,255) , (0,0,255) ,10) 

img =  cv2.arrowedLine(img, (0,255) , (255,255) , (255,0,0) ,10)

img = cv2.rectangle(img,(384,0),(510,128),(0,0,255),-1) 
#if you give -1 for thickness, it will fill in rectangle the color which you determined for around the rectangle.



cv2.imshow("image",img)

cv2.waitKey(0)
cv2.destroyAllWindows()

In [31]:
img = cv2.imread("lena.jpg",1) 

img = cv2.line(img, (0,0) , (255,255) , (0,0,255) ,10) 

img =  cv2.arrowedLine(img, (0,255) , (255,255) , (255,0,0) ,10)

img = cv2.rectangle(img,(384,0),(510,128),(0,0,255),-1) 
#if you give -1 for thickness, it will fill in rectangle the color which you determined for around the rectangle.

img = cv2.circle(img , (447,63) , 63 , (0,255,0) , -1) #img,center point,radius,color,fill
img = cv2.circle(img , (447,63) , 20 , (0,255,255) , -1)

font = cv2.FONT_HERSHEY_SIMPLEX
img = cv2.putText(img, "Pixel Busters",(10,500), font , 2.3, (0,255,255), 10, cv2.LINE_AA) #if you add red on green, you can obtain yellow



cv2.imshow("image",img)

cv2.waitKey(0)
cv2.destroyAllWindows()

In [32]:
import numpy as np

In [35]:
#img = cv2.imread("lena.jpg",1) 
img = np.zeros([512,512,3], np.uint8) #we can create an image using numpy zeros method.
#it gives us a black colored image

img = cv2.line(img, (0,0) , (255,255) , (0,0,255) ,10) 

img =  cv2.arrowedLine(img, (0,255) , (255,255) , (255,0,0) ,10)

img = cv2.rectangle(img,(384,0),(510,128),(0,0,255),-1) 
#if you give -1 for thickness, it will fill in rectangle the color which you determined for around the rectangle.

img = cv2.circle(img , (447,63) , 63 , (0,255,0) , -1) #img,center point,radius,color,fill

font = cv2.FONT_HERSHEY_SIMPLEX
img = cv2.putText(img, "Pixel Busters",(10,500), font , 2.3, (0,255,255), 10, cv2.LINE_AA) #if you add red on green, you can obtain yellow



cv2.imshow("image",img)

cv2.waitKey(0)
cv2.destroyAllWindows()

# Setting Camera Parameters

In [2]:
import cv2
cap = cv2.VideoCapture(0)
print(cap.get(cv2.CAP_PROP_FRAME_WIDTH))
print(cap.get(cv2.CAP_PROP_FRAME_HEIGHT))

cap.set(3, 1208) #this is for setting frame width #it will be 1280 because of the resolution
cap.set(4, 720) #this is for setting frame height

print(cap.get(3))
print(cap.get(4))

while(cap.isOpened()):
    ret,frame = cap.read()
    if ret == True:
        
        gray = cv2.cvtColor(frame, cv2.COLOR_BGR2GRAY)
        cv2.imshow("frame", gray)
        
        if cv2.waitKey(50000) & 0xFF == ord("q"):
            break
        else :
            break

cap.release()
cv2.destroyAllWindows()
    

640.0
480.0
1280.0
720.0


# Showing Date and Time on Videos

In [4]:
import cv2
import datetime

cap = cv2.VideoCapture(0)
print(cap.get(cv2.CAP_PROP_FRAME_WIDTH))
print(cap.get(cv2.CAP_PROP_FRAME_HEIGHT))

#cap.set(3, 1208) #this is for setting frame width #it will be 1280 because of the resolution
#cap.set(4, 720) #this is for setting frame height

print(cap.get(3))
print(cap.get(4))

while(cap.isOpened()):
    ret,frame = cap.read()
    if ret == True:
        
        font = cv2.FONT_HERSHEY_SIMPLEX
        text = "Width:" + str(cap.get(3)) + " Height:" + str(cap.get(4))
        datet = str(datetime.datetime.now())
        frame = cv2.putText(frame, datet, (10,50), font, 1 , (0,255,255), 2, cv2.LINE_AA )
        cv2.imshow("frame", frame)
        
        if cv2.waitKey(50000) & 0xFF == ord("q"):
            break
        else:
            break
        

cap.release()
cv2.destroyAllWindows()


640.0
480.0
640.0
480.0


# Handle Mouse Events

In [7]:
events = [i for i in dir(cv2) if "EVENT" in i]
print(events) #dir cv2 gives all functions,classes and variables names in cv2 package

def click_event(event, x, y, flags, param): 
    if event == cv2.EVENT_LBUTTONDOWN:
        print(x , ", " , y)
        font = cv2.FONT_HERSHEY_SIMPLEX
        strXY = str(x) + ", " + str(y)
        frame = cv2.putText(img, strXY, (x, y), font, .5, (255,255,0), 2)
        cv2.imshow("image",img)
    
    if event == cv2.EVENT_RBUTTONDOWN: #koyduğumuz image siyah olduğundan bgr channelları (0,0,0) olacak.
        blue = img[y,x,0]
        green = img[y,x,1]
        red = img[y,x,2]
        font = cv2.FONT_HERSHEY_SIMPLEX
        strBGR = str(blue) + ", " + str(green) + ", " + str(red)
        frame = cv2.putText(img, strBGR, (x, y), font, .5, (0,255,255), 2)
        cv2.imshow("image",img)
        
img = np.zeros([512,512,3], np.uint8)
#img = cv2.imread("lena.jpg")
cv2.imshow("image",img)

cv2.setMouseCallback("image",click_event)

cv2.waitKey(0)
cv2.destroyAllWindows()


['EVENT_FLAG_ALTKEY', 'EVENT_FLAG_CTRLKEY', 'EVENT_FLAG_LBUTTON', 'EVENT_FLAG_MBUTTON', 'EVENT_FLAG_RBUTTON', 'EVENT_FLAG_SHIFTKEY', 'EVENT_LBUTTONDBLCLK', 'EVENT_LBUTTONDOWN', 'EVENT_LBUTTONUP', 'EVENT_MBUTTONDBLCLK', 'EVENT_MBUTTONDOWN', 'EVENT_MBUTTONUP', 'EVENT_MOUSEHWHEEL', 'EVENT_MOUSEMOVE', 'EVENT_MOUSEWHEEL', 'EVENT_RBUTTONDBLCLK', 'EVENT_RBUTTONDOWN', 'EVENT_RBUTTONUP']
70 ,  51
380 ,  56
408 ,  359
86 ,  357
264 ,  201
73 ,  206
278 ,  101


In [10]:
events = [i for i in dir(cv2) if "EVENT" in i]
print(events) #dir cv2 gives all functions,classes and variables names in cv2 package

def click_event(event, x, y, flags, param): 
    if event == cv2.EVENT_LBUTTONDOWN:
        cv2.circle(img, (x,y), 3, (0,0,255), -1) #remember that 3 gives radius and -1 says that fill the circle.
        points.append((x,y))
        if len (points) >= 2:
            cv2.line(img, points[-1], points[-2], (255,0,0), 5)
        cv2.imshow("image",img)
    
    
img = np.zeros([512,512,3], np.uint8)
#img = cv2.imread("lena.jpg")
cv2.imshow("image",img)
points = []

cv2.setMouseCallback("image",click_event)

cv2.waitKey(0)
cv2.destroyAllWindows()

['EVENT_FLAG_ALTKEY', 'EVENT_FLAG_CTRLKEY', 'EVENT_FLAG_LBUTTON', 'EVENT_FLAG_MBUTTON', 'EVENT_FLAG_RBUTTON', 'EVENT_FLAG_SHIFTKEY', 'EVENT_LBUTTONDBLCLK', 'EVENT_LBUTTONDOWN', 'EVENT_LBUTTONUP', 'EVENT_MBUTTONDBLCLK', 'EVENT_MBUTTONDOWN', 'EVENT_MBUTTONUP', 'EVENT_MOUSEHWHEEL', 'EVENT_MOUSEMOVE', 'EVENT_MOUSEWHEEL', 'EVENT_RBUTTONDBLCLK', 'EVENT_RBUTTONDOWN', 'EVENT_RBUTTONUP']


In [9]:
events = [i for i in dir(cv2) if "EVENT" in i]
print(events) #dir cv2 gives all functions,classes and variables names in cv2 package

def click_event(event, x, y, flags, param): 
        blue = img[y,x,0]
        green = img[y,x,1]
        red = img[y,x,2]
        cv2.circle(img, (x,y), 3, (0,0,255), -1)
        mycolorImage = np.zeros([512,512,3], np.uint8)
        
        mycolorImage[:] = [blue,green,red]
        
        cv2.imshow("color",mycolorImage)
    
    
#img = np.zeros([512,512,3], np.uint8)
img = cv2.imread("lena.jpg")
cv2.imshow("image",img)
points = []

cv2.setMouseCallback("image",click_event)

cv2.waitKey(0)
cv2.destroyAllWindows()

['EVENT_FLAG_ALTKEY', 'EVENT_FLAG_CTRLKEY', 'EVENT_FLAG_LBUTTON', 'EVENT_FLAG_MBUTTON', 'EVENT_FLAG_RBUTTON', 'EVENT_FLAG_SHIFTKEY', 'EVENT_LBUTTONDBLCLK', 'EVENT_LBUTTONDOWN', 'EVENT_LBUTTONUP', 'EVENT_MBUTTONDBLCLK', 'EVENT_MBUTTONDOWN', 'EVENT_MBUTTONUP', 'EVENT_MOUSEHWHEEL', 'EVENT_MOUSEMOVE', 'EVENT_MOUSEWHEEL', 'EVENT_RBUTTONDBLCLK', 'EVENT_RBUTTONDOWN', 'EVENT_RBUTTONUP']


# Basic Arithmetic Operations on Images

In [12]:
img = cv2.imread("messi5.jpg")

print(img.shape) #returns a tuple of number of rows, columns, and channels
print(img.size) #returns total number of pixels are accessed
print(img.dtype) #return image datatype is obtained
b,g,r = cv2.split(img)
img = cv2.merge((b,g,r)) #we splitted our image into three channels, and if you want to return an original image again, run this codeg
cv2.imshow("image",img) #you can change channel on this code according to which channel you would like to see.
cv2.waitKey(0) 
cv2.destroyAllWindows()

(342, 548, 3)
562248
uint8


In [14]:
img = cv2.imread("messi5.jpg")
img2 = cv2.imread("opencv-logo.png") #it has same size with messi image.

print(img.shape) #returns a tuple of number of rows, columns, and channels
print(img.size) #returns total number of pixels are accessed
print(img.dtype) #return image datatype is obtained
b,g,r = cv2.split(img)
img = cv2.merge((b,g,r)) #we splitted our image into three channels, and if you want to return an original image again, run this code

#here our region of interest(roi) is ball.it could be face or something.
ball = img[280:340,330:390] #these are top-left and bottom right coordinates of the ball. 
#if you don't know these coordinates you can also use methods that we have aldready used.
img[273:333,100:160] = ball #you're putting a ball into this coordinates.

img = cv2.resize(img, (512,512)) #these two images should have same sizes.
img2 = cv2.resize(img2, (512,512))

#dst = cv2.add(img,img2)
dst = cv2.addWeighted(img,.6,img2,.4,0) #we're giving weights to the image in this code.




cv2.imshow("image",dst)
cv2.waitKey(0) 
cv2.destroyAllWindows()

(342, 548, 3)
562248
uint8


# Bitwise Operations (AND,OR,NOT and XOR)

In [16]:
img1 = cv2.imread("messi5.jpg")
img2 = cv2.imread("opencv-logo.png")

img1 = cv2.resize(img1, (512,512)) #these two images should have same sizes.
img2 = cv2.resize(img2, (512,512))

#bitAnd = cv2.bitwise_and(img2, img1)
#bitOr = cv2.bitwise_or(img2, img1)
#bitXor = cv2.bitwise_xor(img2,img1)
bitNot1 = cv2.bitwise_not(img1)
bitNot2 = cv2.bitwise_not(img2)


cv2.imshow("img1", img1)
cv2.imshow("img2", img2)

#cv2.imshow("bitAnd",bitAnd)
#cv2.imshow("bitOr",bitOr)
#cv2.imshow("bitXor",bitXor)
cv2.imshow("bitNot1",bitNot1) 
cv2.imshow("bitNot2",bitNot2)



cv2.waitKey(0)
cv2.destroyAllWindows()

# How to Bind Trackbar To OpenCV Windows

In [ ]:
def nothing(x):
    print(x)

img = np.zeros((300,512,3), np.uint8)
cv2.namedWindow("image")

cv2.createTrackbar("B", "image", 0, 255, nothing)
cv2.createTrackbar("G", "image", 0, 255, nothing)
cv2.createTrackbar("R", "image", 0, 255, nothing)

switch = "0  : OFF\n 1 : ON"
cv2.createTrackbar(switch,"image", 0, 1, nothing)



while(1):
    cv2.imshow("image", img)
    k = cv2.waitKey(1) & 0xFF
    if k == 27:
        break
        
    b = cv2.getTrackbarPos("B", "image")
    g = cv2.getTrackbarPos("G", "image")
    r = cv2.getTrackbarPos("R", "image")
    s = cv2.getTrackbarPos(switch, "image")
    
    if s == 0:
        img[:] = 0
    else :
        img[:] = [b,g,r]

cv2.destroyAllWindows()

1
1
2
4
6
7
9
12
13
15
19
21
23
25
28
30
31
33
34
37
38
39
41
43
46
47
50
52
55
57
62
67
73
78
82
85
91
93
98
103
105
107
111
115
118
120
122
124
126
127
129
130
134
136
138
139
140
142
143
144
147
149
150
152
154
158
162
165
168
170
173
175
176
177
178
180
182
183
185
188
192
195
201
203
206
208
210
211
213
215
216
217
218
219
220
221
224
227
228
230
231
232
233
255
1
2
4
6
11
13
17
20
24
29
34
40
45
49
56
62
68
75
79
84
89
94
98
104
115
123
131
139
146
152
159
167
173
178
180
182
185
187
188
190
192
194
196
201
207
212
215
219
223
225
226
228
231
233
236
237
238
241
242
244
246
248
249
251
252
254
255
1
2
3
8
10
14
18
24
29
34
39
45
50
57
64
70
78
84
92
106
119
131
141
149
159
166
173
177
182
185
188
193
196
200
203
206
209
212
214
217
219
221
223
226
227
229
231
233
234
236
241
242
244
245
246
249
251
253
255
250
248
244
238
232
226
220
214
208
202
199
197
194
192
190
188
186
184
181
179
177
174
171
168
165
162
157
154
150
146
143
137
132
129
123
118
111
106
101
90
78
69
59
52
42
40

In [ ]:
def nothing(x):
    print(x)


cv2.namedWindow("image")

cv2.createTrackbar("CP", "image", 10, 1000, nothing)


switch = "color/gray"
cv2.createTrackbar(switch,"image", 0, 1, nothing)



while(1):
    img = cv2.imread("lena.jpg")
    
    pos = cv2.getTrackbarPos("CP", "image")
    font = cv2.FONT_HERSHEY_SIMPLEX
    cv2.putText(img, str(pos), (50, 150), font, 6, (0, 0, 255), 10)
    
    
    k = cv2.waitKey(1) & 0xFF
    if k== 27:
        break
        
    s = cv2.getTrackbarPos(switch, "image")
  
    
    if s == 0:
        pass
    else :
        img = cv2.cvtColor(img, cv2.COLOR_BGR2GRAY)
    img = cv2.imshow("image", img)

cv2.destroyAllWindows()


14
17
23
25
28
31
34
42
48
54
62
76
82
90
101
110
130
144
152
161
163
169
172
177
183
186
194
200
220
228
239
251
254
256
265
270
276
279
282
285
287
290
293
296
299
301
304
307
313
315
321
324
327
332
338
341
346
361
366
372
377
380
389
392
394
397
403
414
423
431
437
442
451
456
465
470
479
482
490
496
499
501
504
507
510
518
527
538
544
552
555
558
561
566
569
572
577
777
783
786
794
797
800
806
814
817
828
834
839
845
851
856
1000
997
992
986
980
977
969
966
961
952
946
930
918
901
887
848
828
806
766
749
724
713
699
687
679
665
654
645
637
623
611
597
577
561
532
515
496
468
454
442
411
397
383
372
335
321
307
287
268
254
242
225
214
206
194
183
172
161
146
124
110
99
79
65
51
37
25
8
0


# Object Detection and Object Tracking Using HSV Color Space

In [ ]:
#we would like to find blue balls in the image.
def nothing(x):
    pass

cv2.namedWindow("Tracking") #hsv color space'i öğrenmek istediğinde bu kodu kullanabilirsin.if you don't know upper and lower bound.
cv2.createTrackbar("LH", "Tracking", 0, 255, nothing) #lower hue
cv2.createTrackbar("LS", "Tracking", 0, 255, nothing) #lower saturation
cv2.createTrackbar("LV", "Tracking", 0, 255, nothing) #lower value
cv2.createTrackbar("UH", "Tracking", 255, 255, nothing) #upper hue
cv2.createTrackbar("US", "Tracking", 255, 255, nothing) #upper saturation
cv2.createTrackbar("UV", "Tracking", 255, 255, nothing) #upper value


while(True):
    frame = cv2.imread("smarties.png")
    
    hsv = cv2.cvtColor(frame, cv2.COLOR_BGR2HSV)
    
    l_h = cv2.getTrackbarPos("LH", "Tracking")
    l_s = cv2.getTrackbarPos("LS", "Tracking")
    l_v = cv2.getTrackbarPos("LV", "Tracking")
    
    u_h = cv2.getTrackbarPos("UH", "Tracking")
    u_s = cv2.getTrackbarPos("US", "Tracking")
    u_v = cv2.getTrackbarPos("UV", "Tracking")
    
    
    l_b = np.array([l_h,l_s,l_v]) #lower blue : finding the lower blue and upper blue is not easy so we should use trackbar.
    u_b = np.array([u_h,u_s,u_v])
    
    mask = cv2.inRange(hsv, l_b, u_b)
    
    res = cv2.bitwise_and(frame, frame, mask = mask) 
    
    cv2.imshow("frame", frame)
    cv2.imshow("mask", mask)
    cv2.imshow("result", res)
    
    
    
    key = cv2.waitKey(1)
    if key == 27:
        break
        
cv2.destroyAllWindows()
        

In [ ]:
#we would like to find blue balls in the image.
def nothing(x):
    pass

cap = cv2.VideoCapture(0) #we're doing the same process here but for videos.

cv2.namedWindow("Tracking") #hsv color space'i öğrenmek istediğinde bu kodu kullanabilirsin.if you don't know upper and lower bound.
cv2.createTrackbar("LH", "Tracking", 0, 255, nothing) #lower hue
cv2.createTrackbar("LS", "Tracking", 0, 255, nothing) #lower saturation
cv2.createTrackbar("LV", "Tracking", 0, 255, nothing) #lower value
cv2.createTrackbar("UH", "Tracking", 255, 255, nothing) #upper hue
cv2.createTrackbar("US", "Tracking", 255, 255, nothing) #upper saturation
cv2.createTrackbar("UV", "Tracking", 255, 255, nothing) #upper value


while(True):
    _, frame = cap.read()
    
    hsv = cv2.cvtColor(frame, cv2.COLOR_BGR2HSV)
    
    l_h = cv2.getTrackbarPos("LH", "Tracking")
    l_s = cv2.getTrackbarPos("LS", "Tracking")
    l_v = cv2.getTrackbarPos("LV", "Tracking")
    
    u_h = cv2.getTrackbarPos("UH", "Tracking")
    u_s = cv2.getTrackbarPos("US", "Tracking")
    u_v = cv2.getTrackbarPos("UV", "Tracking")
    
    
    l_b = np.array([l_h,l_s,l_v]) #lower blue : finding the lower blue and upper blue is not easy so we should use trackbar.
    u_b = np.array([u_h,u_s,u_v])
    
    mask = cv2.inRange(hsv, l_b, u_b)
    
    res = cv2.bitwise_and(frame, frame, mask = mask) 
    
    cv2.imshow("frame", frame)
    cv2.imshow("mask", mask)
    cv2.imshow("result", res)
    
    
    
    key = cv2.waitKey(1)
    if key == 27:
        break

cap.release()
cv2.destroyAllWindows()

# Simple Image Thresholding

In [2]:
img = cv2.imread("gradient.png")

cv2.imshow("Image", img)

cv2.waitKey(0)
cv2.destroyAllWindows()